Repository boostcampwm-2024/refactor-web31-BooLock, pull requests merged in 2025-01, with the labels that each got.

#12 [#1] Docker 이미지 최적화
  .github/workflows/boolock-dev-cicd.yml
  apps/client/Dockerfile
  apps/client/package.json
  apps/server/Dockerfile
  apps/server/package.json
  apps/server/src/app.ts
  apps/server/tsconfig.json
  pnpm-lock.yaml
Labels: BE, refactor, setting

#15 [#11] Google Analytics 적용
  apps/client/index.html
Labels: FE, refactor

#19 [#18] useQuery, useInfiniteQuery -> useSuspenseQuery, useSuspenseInfiniteQuery 교체
  apps/client/src/app/App.tsx
  apps/client/src/pages/HomePage/HomePage.tsx
  apps/client/src/pages/WorkspaceErrorPage/WorkspaceErrorPage.tsx
  apps/client/src/pages/Workspacepage/WorkspacePage.tsx
  apps/client/src/pages/index.ts
  apps/client/src/shared/hooks/queries/useGetWorkspace.ts
  apps/client/src/shared/hooks/queries/useGetWorkspaceList.ts
  apps/client/src/widgets/home/WorkspaceContainer/WorkspaceContainer.stories.tsx
  apps/client/src/widgets/home/WorkspaceContainer/WorkspaceContainer.tsx
  apps/client/src/widgets/home/WorkspaceSection/WorkspaceSection.stories.tsx
  apps/client/src/widgets/home/WorkspaceSection/WorkspaceSection.tsx
  apps/client/src/widgets/index.ts
  apps/server/src/middlewares/errorMiddleware.ts
  apps/server/src/utils/customError.ts
Labels: refactor

#22 [#21] 홈페이지 로딩 시 스켈레톤UI에 그리드가 적용되지 않는 문제 해결, 워크스페이스 로딩 화면 조건부 렌더링
  apps/client/src/app/App.tsx
  apps/client/src/shared/ui/index.ts
  apps/client/src/shared/ui/loading/DelayedFallback.tsx
  apps/client/src/widgets/home/WorkspaceSection/WorkspaceSection.tsx
Labels: bug

#27 [#20] HTTP개선 (1.1 -> 2.0 -> 3.0)
  apps/client/production/nginx.conf
Labels: refactor

#36 [#31] “Code 하이라이팅” 코드 품질 개선
  apps/client/src/shared/code-highlighter/components/CodeContent/CodeContent.stories.tsx
  apps/client/src/shared/code-highlighter/components/CodeContent/CodeContent.tsx
  apps/client/src/shared/code-highlighter/components/CodeViewer/CodeViewer.tsx
  apps/client/src/shared/code-highlighter/components/LineNumbers/LineNumbers.tsx
  apps/client/src/shared/code-highlighter/components/index.ts
  apps/client/src/shared/code-highlighter/constants/index.ts
  apps/client/src/shared/code-highlighter/hooks/index.ts
  apps/client/src/shared/code-highlighter/hooks/useDiffCodeAnimate.ts
  apps/client/src/shared/code-highlighter/hooks/useHoverLineNumber.ts
  apps/client/src/shared/code-highlighter/types/index.ts
  apps/client/src/shared/code-highlighter/utils/getClassNames.ts
  apps/client/src/shared/code-highlighter/utils/getLineNumberClass.ts
  apps/client/src/shared/code-highlighter/utils/getParsedCodeLineList.ts
  apps/client/src/shared/code-highlighter/utils/getViewerClassNames.ts
  apps/client/src/shared/code-highlighter/utils/index.ts
  apps/client/src/shared/code-highlighter/utils/parseHighlightCss.ts
  apps/client/src/shared/code-highlighter/utils/parseHighlightHtml.ts
Labels: refactor

#35 [#26] 워크스페이스 페이지의 불필요한 리렌더링 개선
  apps/client/src/entities/workspace/CssCategoryButton/CssCategoryButton.tsx
  apps/client/src/entities/workspace/CssOptionItem/CssOptionItem.tsx
  apps/client/src/entities/workspace/CssTooltip/CssTooltip.stories.tsx
  apps/client/src/entities/workspace/CssTooltip/CssTooltip.tsx
  apps/client/src/entities/workspace/SaveButton/SaveButton.tsx
  apps/client/src/pages/Workspacepage/WorkspacePage.tsx
  apps/client/src/shared/hooks/css/useCssClassList.ts
  apps/client/src/shared/hooks/css/useCssOptionItem.ts
  apps/client/src/shared/hooks/css/useCssOptions.ts
  apps/client/src/shared/hooks/css/useCssTooltip.ts
  apps/client/src/shared/hooks/index.ts
  apps/client/src/shared/hooks/queries/useGetWorkspace.ts
  apps/client/src/shared/store/index.ts
  apps/client/src/shared/store/useCssPropsStore.ts
  apps/client/src/shared/store/useCssTooptipStore.ts
  apps/client/src/shared/types/customSelectType.ts
  apps/client/src/shared/types/index.ts
  apps/client/src/shared/ui/index.ts
  apps/client/src/shared/ui/select/Select.tsx
  apps/client/src/widgets/workspace/WorkspaceContent/WorkspaceContent.tsx
  apps/client/src/widgets/workspace/css/CssOptionItemList/CssOptionItemList.tsx
  apps/client/src/widgets/workspace/css/CssPropsSelectBoxHeader/CssPropsSelectBoxHeader.tsx
Labels: refactor

#37 [#25] 사용자가이드 단계 이동시 헤더 내 모든 요소 리렌더링 개선
  apps/client/src/entities/index.ts
  apps/client/src/entities/workspace/CodeExportButton/CodeExportButton.tsx
  apps/client/src/entities/workspace/HelpButton/HelpButton.tsx
  apps/client/src/entities/workspace/RedoButton/RedoButton.tsx
  apps/client/src/entities/workspace/SaveButton/SaveButton.tsx
  apps/client/src/entities/workspace/UndoButton/UndoButton.tsx
  apps/client/src/entities/workspace/WorkspaceNameInput/WorkspaceNameInput.tsx
  apps/client/src/pages/Workspacepage/WorkspacePage.tsx
  apps/client/src/shared/ui/logo/Logo.tsx
  apps/client/src/widgets/workspace/WorkspaceHeaderButtons/WorkspaceHeaderButtons.tsx
  apps/client/src/widgets/workspace/WorkspacePageHeader/WorkspacePageHeader.tsx
Labels: refactor

#38 [#34] 수동 저장 -> 자동 저장으로 변경
  apps/client/src/entities/workspace/SaveButton/SaveButton.tsx
  apps/client/src/shared/hooks/capturePreview.worker.ts
  apps/client/src/shared/hooks/queries/useSaveWorkspace.ts
  apps/client/src/shared/hooks/usePreventLeaveWorkspacePage.ts
  apps/client/src/shared/hooks/useWorkspaceSave.ts
  apps/client/src/shared/utils/capturePreview.ts
  apps/client/src/shared/utils/convertToCanvas.ts
  apps/client/src/shared/utils/index.ts
  apps/client/src/widgets/workspace/PreviewBox/PreviewBox.tsx
  apps/client/src/widgets/workspace/WorkspaceContent/WorkspaceContent.tsx
  apps/client/src/widgets/workspace/WorkspaceHeaderButtons/WorkspaceHeaderButtons.tsx
  apps/client/vite.config.ts
Labels: refactor
